Add add_local_campaign example
googleads/google-ads-perl pull request #40
Opened 2020-09-16 15:03 UTC by wfansh

2020-09-16 16:53 UTC, jradcliff reviewed
Very minor suggestions

2020-09-16 16:53 UTC, jradcliff commented on examples/advanced_operations/add_local_campaign.pl
> +  # Since the advertisingChannelSubType is LOCAL_CAMPAIGN,
nit: s/,/:/

2020-09-16 16:53 UTC, jradcliff commented on examples/advanced_operations/add_local_campaign.pl
> +  #   1- you cannot override bid settings at the ad group level.
nit: I think `1.` instead of `1-` is more common, but is `1-` the standard way to do a #'d list in Perl comments?

2020-09-17 04:40 UTC, fiboknacky requested changes
Is this a draft or working example?

2020-09-17 04:40 UTC, fiboknacky commented on examples/advanced_operations/add_local_campaign.pl
> +  # Create the campaign.
Nit: I think it should be:

\# Create "a" budget
\# Create "a" campaign
\# Create "an" ad group.

2020-09-17 04:40 UTC, fiboknacky commented on examples/advanced_operations/add_local_campaign.pl
> +      # direction and/or call clicks to optimize for those actions in your campaign.
Are there only two types of optimization goals?
Are there Help Center articles that describe this?

2020-09-17 04:40 UTC, fiboknacky commented on examples/advanced_operations/add_local_campaign.pl
> +sub create_ad_text_asset {
This is not called yet.

2020-09-17 06:00 UTC, wfansh commented on examples/advanced_operations/add_local_campaign.pl
> +      # direction and/or call clicks to optimize for those actions in your campaign.
Please see https://support.google.com/google-ads/answer/9118358?hl=en for chapter 4, but STORE_VISITS is still not supported in v5 proto files.

p.s. you can login to my CID (78369355572) to take a look at any Local campaign

https://screenshot.googleplex.com/6Yf3VGUP5EU88iY

2020-09-17 06:01 UTC, wfansh commented on examples/advanced_operations/add_local_campaign.pl
> +  # Create the campaign.
Done

2020-09-17 13:35 UTC, wfansh commented
> Is this a draft or working example?

2020-09-17 13:36 UTC, wfansh commented
This example is working now -> if the CID is connected with a GMB

2020-09-17 14:29 UTC, fiboknacky reviewed
Is this example runnable more than once? Will there be any errors of the asset service?

2020-09-17 14:47 UTC, wfansh commented
> Is this example runnable more than once? Will there be any errors of the asset service?

This is a good question. Yes it can run multiple times, and there's no error from the AssetService when uploading the same image/video more than once with the **same name**. 

Actually the image has been uploaded by other code examples such as [add_smart_display_ad](https://github.com/googleads/google-ads-perl/blob/master/examples/advanced_operations/add_smart_display_ad.pl#L72), 
[add_gmail_ad](https://github.com/googleads/google-ads-perl/blob/master/examples/advanced_operations/add_gmail_ad.pl#L48
). The AssetService returns the same resource name if the image is uploaded already; but it fails if you try to specify a different asset name.

This is a lesson learnt for me when developing the FT application.

2020-09-17 14:51 UTC, fiboknacky approved these changes

2020-09-23 23:29 UTC, jradcliff commented on examples/advanced_operations/add_local_campaign.pl
> +                    )})]})})}
Does the formatter put this long string of brackets and parentheses on the same line? Seems very difficult to read.

2020-09-23 23:29 UTC, jradcliff commented on examples/advanced_operations/add_local_campaign.pl
> +      # direction and/or call clicks to optimize for those actions in your campaign.
To ensure this comment does not become outdated when/if additional goal settings become available, you could say:

```
# Optimization goal setting is mandatory for Local campaigns. This example selects
# driving directions and call clicks as goals.
```

2020-09-24 11:07 UTC, wfansh commented on examples/advanced_operations/add_local_campaign.pl
> +                    )})]})})}
Yes, it's the behavior of the formatter. We use Perl::Tidy to format the code, and the format is defined as below (reused from WebAPI library.)

https://github.com/googleads/google-ads-perl/blob/master/.perltidyrc

2020-09-24 11:12 UTC, wfansh commented on examples/advanced_operations/add_local_campaign.pl
> +      # direction and/or call clicks to optimize for those actions in your campaign.
Thanks Josh, this seems much better. Updated.

2020-09-24 11:16 UTC, wfansh commented
# Optimization goal setting is mandatory for Local campaigns. This example
      # selects driving directions and call clicks as goals.

2020-09-24 12:49 UTC, jradcliff approved these changes

2020-09-24 12:49 UTC, jradcliff commented on examples/advanced_operations/add_local_campaign.pl
> +                    )})]})})}
Thanks for confirming. I'd hope it would split this up a bit more, but I also don't think we want to manually modify the format here. It'll just get reverted the next time you format. :)

2020-09-24 12:58 UTC, wfansh commented on examples/advanced_operations/add_local_campaign.pl
> +                    )})]})})}
That's true~
Thanks a lot Josh

2020-09-24 12:58 UTC, merged