Added: example to exclude IP addresses from the campaign.
googleads/google-ads-perl pull request #98
Opened 2023-02-17 17:16 UTC by Abhinickz

Fix: https://github.com/googleads/google-ads-perl/issues/97 Added: example to exclude IP addresses from the campaign by updating campaign_criterion.

2023-02-23 01:14 UTC, laurachevalier4 requested changes
Thanks for this PR! Just a few changes before it can be merged.

2023-02-23 01:14 UTC, laurachevalier4 commented on examples/campaign_management/update_campaign_criterion_ip_block.pl
> +        # for removing the IP from the campaign criterion
Can you update this comment to say:
```
# To remove the IP block campaign criterion, use:
# remove => <campaign_criterion_resource_name>
```

2023-02-23 01:14 UTC, laurachevalier4 commented on examples/campaign_management/update_campaign_criterion_ip_block.pl
> +  # Issue a mutate request to update the excluded IPs of campaign criterion.
Can you update this to:
```
# Issue a mutate request to create the campaign criteria for the IP addresses to exclude.
```

2023-02-24 15:01 UTC, Abhinickz commented on examples/campaign_management/update_campaign_criterion_ip_block.pl
> +use Google::Ads::GoogleAds::V12::Resources::CampaignCriterion;
Updated `V12` to `V13` in this example file.

2023-02-24 15:02 UTC, Abhinickz commented on examples/campaign_management/update_campaign_criterion_ip_block.pl
> +my $CRITERION_ID = "27";                        # ip_block
ran `perltidy -pro=.perltidyrc examples/campaign_management/update_campaign_criterion_ip_block.pl`

2023-02-24 15:04 UTC, Abhinickz commented
Thanks [laurachevalier4](https://github.com/laurachevalier4) for the PR review.

I have updated the PR with the requested changes.
Please have a look and let me know if anything else needs to be updated.

2023-02-24 16:00 UTC, laurachevalier4 commented on examples/campaign_management/update_campaign_criterion_ip_block.pl
> +# ip_block_criterion_id
To avoid confusion that there's some field called `ip_block_criterion_id`, can you update this to `ip_block criterion ID`?

2023-02-24 16:02 UTC, laurachevalier4 commented on examples/campaign_management/update_campaign_criterion_ip_block.pl
> +
For consistency with other examples, can you remove this blank line? (And on lines 76, 79, and 95)?

2023-02-24 16:35 UTC, Abhinickz commented
[laurachevalier4](https://github.com/laurachevalier4), Updated `ip_block_criterion_id` to `ip_block criterion ID` and removed blank lines for consistency with other examples.
Please review.

2023-02-24 18:30 UTC, laurachevalier4 approved these changes

2023-02-24 18:30 UTC, merged